#!/usr/bin/env bash
# This script verificate states for a file

device=school

if [ -e $device ]; then
	echo "school file exists"

	if [ -s $device ]; then
		echo "school file is not empty"
	fi
	if [ ! -s $device ]; then 
                echo "school file is emtpy"
	fi
	if [ -f $device ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
